TestSuite([
    'CoreTest',
    'AjaxTest',
    'Ajax.RequestTest',
    'UtilTest',
    'Resource.DefaultLoaderTest',
    'Resource.LoaderTest',
    'Template.DefaultReaderTest',
    'ActiveRecordTest',
    'DataProvider.LocalTest'
]);